board:
  name: ESP32-S3 DevKit
  target: esp32s3
  build:
    type: idf
    project_dir: firmware/targets/esp32s3
  flash:
    method: idf_esptool
    port: null
    baud: 460800
    serial: "80:B5:4E:C3:9C:7C"
  observe_map:
    sig: P0.0
    gpio4: P0.0
    gpio5: P0.1
    gpio6: P0.2
    gpio7: P0.3
  observe:
    la:
      threshold_v: 1.6
      default_sample_rate_hz: 260000
  pins:
    safe_output:
      - GPIO4
      - GPIO5
      - GPIO6
      - GPIO7
      - GPIO48
    strap_or_reserved:
      - GPIO0
      - GPIO3
      - GPIO46
  default_wiring:
    swd: "P3"
    reset: "NC"
    verify: "P0.0"
