board:
  name: RP2040 Pico
  target: rp2040
  instrument_instance: esp32jtag_rp2040_lab
  firmware:
    description: Blink GPIO25 ~1Hz
  observe_map:
    sig: P0.0
  default_wiring:
    swd: "P3"
    reset: "P2.0"
    verify: "PA0"
