board:
  name: STM32F103 Bluepill
  target: stm32f103c8t6
  firmware:
    description: Toggle PA4-PA7 fast, blink PC13
  flash:
    speed_khz: 1000
    reset_strategy: connect_under_reset
    target_id: 1
    gdb_launch_cmds:
      - "file {firmware}"
      - "monitor a"
      - "attach {target_id}"
      - "load"
      - "detach"
  observe_map:
    sig: P0.0
    pa4: P0.0
    pa5: P0.1
    pa6: P0.2
    pa7: P0.3
  safe_pins:
    - PA4
    - PA5
    - PA6
    - PA7
    - PC13
  default_wiring:
    swd: "P3"
    reset: "NC"
    verify: "P0.0"
