if (DEFINED ENV{PICO_SDK_PATH})
    set(PICO_SDK_PATH $ENV{PICO_SDK_PATH})
endif ()
if (NOT PICO_SDK_PATH)
    get_filename_component(_AEL_REPO_ROOT "${CMAKE_CURRENT_LIST_DIR}/../../../../../../.." ABSOLUTE)
    set(PICO_SDK_PATH "${_AEL_REPO_ROOT}/../github/pico-sdk")
endif ()
if (NOT EXISTS "${PICO_SDK_PATH}/external/pico_sdk_import.cmake")
    message(FATAL_ERROR "PICO_SDK_PATH not found: ${PICO_SDK_PATH}")
endif ()
include("${PICO_SDK_PATH}/external/pico_sdk_import.cmake")
