{
  "execution_policy": {
    "kind": "serial"
  },
  "mode": "sequence",
  "steps": [
    {
      "board": "esp32c6_devkit",
      "test": "tests/plans/esp32c6_gpio_signature_with_meter.json"
    },
    {
      "board": "rp2040_pico",
      "test": "tests/plans/rp2040_gpio_signature.json"
    },
    {
      "board": "stm32f103_gpio",
      "test": "tests/plans/stm32f103_gpio_signature.json"
    },
    {
      "board": "stm32f103_uart",
      "test": "tests/plans/stm32f103_uart_banner.json",
      "optional": true
    },
    {
      "board": "stm32f411ceu6",
      "test": "tests/plans/stm32f411_gpio_signature.json"
    }
  ],
  "stop_on_fail": false,
  "version": 1
}
