probe:
  name: ESP32JTAG
  transport: wifi
  wifi_mode: AP
  web_scheme: https
  web_port: 443
  web_user: admin
  web_pass: admin
  web_verify_ssl: false
  web_suppress_ssl_warnings: true

connection:
  ip: 192.168.4.1
  gdb_port: 4242

gdb_cmd: "arm-none-eabi-gdb"

ports:

  P0:
    lines:
      0:
        capabilities: [gpio_in, gpio_out]
      1:
        capabilities: [gpio_in]
        recommended_use: verify_input

  P1:
    lines:
      0:
        capabilities: [adc_in]
        note: analog sampling
      1:
        capabilities: [gpio_in, gpio_out]

  P2:
    lines:
      0:
        capabilities: [reset_out]
        drive: open_drain
        recommended_use: target_reset
      1:
        capabilities: [gpio_out]

  P3:
    capabilities: [swd]
    signals:
      swdio: true
      swclk: true

features:

  sampling:
    digital:
      max_rate_hz: 10000000
      buffer_kb: 1024

  logic_analyzer:
    supported: true
    max_rate_hz: 264000000
    buffer_kb: 1024

  adc:
    supported: true

defaults:
  swd_port: P3
  reset_line: P2.0
  verify_gpio: P0.1

notify:
  discord:
    enabled: true
    webhook_url: "https://discord.com/api/webhooks/1477685561086054431/O-RrP4eYtfGJFgQufVuXwGgEEJgSyD-tqq046bHd4hJkLA2D_HPVw95ha6ctjzpDWiOK"
    notify_on:
      - run_failed
      - need_input
    include_success: true
    mention: ""
    max_log_lines: 20
